---
- name: add deadsnakes repository
  become: true
  apt_repository:
    repo: "{{ item }}"
    update_cache: true
  with_items:
    - ppa:deadsnakes/ppa

- name: install Python
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3.8
    - python3.8-dev

- name: install pip dependencies
  pip:
    state: "latest"
    requirements: "{{ project_path }}/requirements.txt"
