---
- name: check
  hosts: localhost
  roles:
    - local

- name: run
  hosts: cloud
  gather_facts: true
  roles:
    - users
    - server
    - monitoring
    - airflow

  vars_files:
    - ./vars/vars.yml
    - ./secrets/vars.yml
