---
- name: restart airflow-webserver
  systemd:
    name: airflow-webserver
    state: restarted
  when: >-
    airflow_services['airflow_webserver']
    and airflow_services['airflow_webserver']['enabled']
- name: restart airflow-scheduler
  systemd:
    name: airflow-scheduler
    state: restarted
  when: >-
    airflow_services['airflow_scheduler']
    and airflow_services['airflow_scheduler']['enabled']
- name: restart airflow-worker
  systemd:
    name: airflow-worker
    state: restarted
  when: >-
    airflow_services['airflow_worker']
    and airflow_services['airflow_worker']['enabled']
