---
- name: Add deadsnakes repository
  become: true
  apt_repository:
    repo: "{{ item }}"
    update_cache: true
  with_items:
    - ppa:deadsnakes/ppa

- name: Upgrade apt packages
  become: true
  become_method: sudo
  apt:
    name: "*"
    state: latest

- name: Install python3.8 packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3.8
    - python3.8-dev
    - python3.8-venv
    - python3-pip

- name: Upgrade pip
  pip:
    name: pip
    extra_args: --upgrade
    virtualenv: /home/{{ app_user }}/env
    virtualenv_command: "python3.8 -m venv"

- name: Install python dependencies
  pip:
    name: "{{item}}"
    virtualenv: /home/{{ app_user }}/env
    virtualenv_command: "python3.8 -m venv"
  with_lines: cat ./requirements.txt
