---
- name: Add apt repositories
  become: true
  apt_repository:
    repo: "{{ item }}"
    update_cache: true
  with_items:
    - ppa:deadsnakes/ppa

- name: Upgrade apt packages
  become: true
  become_method: sudo
  apt:
    name: "*"
    state: latest

- name: Install python{{ python_ver }}
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python{{ python_ver }}
    - python{{ python_ver }}-dev
    - python{{ python_ver }}-venv
    - python3-pip

- name: Add app users group
  become: true
  become_method: sudo
  group:
    name: "{{ app_group }}"
    state: present

- name: Add app user
  become: true
  become_method: sudo
  user:
    name: "{{ app_user }}"
    state: present

- name: Add ssh user to app group
  become: true
  user:
    name: "{{ ansible_ssh_user }}"
    groups: "{{ app_group }}"
    append: yes

- name: Ensure app home directory
  become: true
  become_method: sudo
  file:
    path: "{{ app_home }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: 0775
    state: directory

- name: Upgrade pip
  become: true
  become_user: "{{ app_user }}"
  pip:
    name: pip
    extra_args: --upgrade
    virtualenv: "{{ app_home }}/env"
    virtualenv_command: "python{{ python_ver }} -m venv"

- name: Install python dependencies
  become: true
  become_user: "{{ app_user }}"
  pip:
    name: "{{item}}"
    virtualenv: "{{ app_home }}/env"
    virtualenv_command: "python{{ python_ver }} -m venv"
  with_lines: cat ./requirements.txt
